<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
    <OutputPath>bin\Release\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>jlcUtils</AssemblyName>
    <!-- Disable globbing default compile items to avoid accidentally compiling extra .cs files -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <!-- Explicitly include only the intended source files -->
    <Compile Include="jlcUtils.cs" />
    <Compile Include="DotNetPluginSDK.cs" />
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <!-- Reference the host assembly if present in the project folder -->
    <Reference Include="CSScriptLibrary">
      <HintPath>CSScriptLibrary.dll</HintPath>
	  <Private>true</Private>
    </Reference>
	  <Reference Include="Microsoft.CSharp">
		  <Private>true</Private>
	  </Reference>
    <Reference Include="TC-DotNetPluginHost64">
      <HintPath>TC-DotNetPluginHost64.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="10.0.11" />
  </ItemGroup>
</Project>
